"""Writes Sources/RoadsAndRunesArt/GameIcons.swift from game_icons.json.

Each icon on game-icons.net is a black 512x512 square with the drawing in
white on top. The square is dropped and the drawing kept as one path of
absolute M/L/Q/C/Z (arcs approximated with cubics), which InkPath reads, so
the icons draw anywhere CoreGraphics does: the app, the Watch, `swift test`.

    uv pip install svgelements   # once
    python3 scripts/game_icons.py
"""

from __future__ import annotations

import io
import json
import pathlib
import urllib.request

from svgelements import SVG, Arc, Close, CubicBezier, Line, Move, Path, QuadraticBezier

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "Sources" / "RoadsAndRunesArt" / "GameIcons.swift"
CREDITS = HERE.parent / "GAME_ICONS.md"
RAW = "https://raw.githubusercontent.com/game-icons/icons/master/{}.svg"
AUTHORS = {
    "lorc": ("Lorc", "CC BY 3.0"),
    "delapouite": ("Delapouite", "CC BY 3.0"),
    "skoll": ("Skoll", "CC BY 3.0"),
    "cathelineau": ("Cathelineau", "CC BY 3.0"),
    "caro-asercion": ("Caro Asercion", "CC BY 3.0"),
    "zeromancer": ("Zeromancer", "CC0"),
}


def number(v: float) -> str:
    s = f"{v:.1f}"
    if s.endswith(".0"):
        s = s[:-2]
    return "0" if s == "-0" else s


def path_of(source: str) -> str:
    svg = SVG.parse(io.BytesIO(source.encode()), reify=True)
    out: list[str] = []
    for element in svg.elements():
        if not isinstance(element, Path):
            continue
        box = element.bbox()
        if box and box[0] <= 0.5 and box[1] <= 0.5 and box[2] >= 511.5 and box[3] >= 511.5 and len(element) <= 6:
            continue  # the black square behind the drawing
        element.approximate_arcs_with_cubics()
        for seg in element:
            if isinstance(seg, Move):
                out.append(f"M{number(seg.end.x)} {number(seg.end.y)}")
            elif isinstance(seg, Close):
                out.append("Z")
            elif isinstance(seg, Line):
                out.append(f"L{number(seg.end.x)} {number(seg.end.y)}")
            elif isinstance(seg, QuadraticBezier):
                c, e = seg.control, seg.end
                out.append(f"Q{number(c.x)} {number(c.y)} {number(e.x)} {number(e.y)}")
            elif isinstance(seg, CubicBezier):
                a, b, e = seg.control1, seg.control2, seg.end
                out.append(f"C{number(a.x)} {number(a.y)} {number(b.x)} {number(b.y)} {number(e.x)} {number(e.y)}")
            elif isinstance(seg, Arc):
                raise ValueError("an arc survived approximation")
    return "".join(out)


def main() -> None:
    manifest = json.loads((HERE / "game_icons.json").read_text())
    icons = {k: v for k, v in manifest.items() if not k.startswith("_")}
    cases, paths, authors, credits = [], [], [], []
    for name, key in icons.items():
        svg = urllib.request.urlopen(RAW.format(key), timeout=30).read().decode()
        author, licence = AUTHORS[key.split("/")[0]]
        cases.append(f"    case {name}")
        paths.append(f'        case .{name}: return "{path_of(svg)}"')
        authors.append(f'        case .{name}: return "{author}"')
        credits.append(f"| `{name}` | [{key.split('/')[1]}](https://game-icons.net/1x1/{key}.html) | {author} | {licence} |")
    OUT.write_text(
        "// Generated by scripts/game_icons.py from scripts/game_icons.json. Do not edit by hand.\n"
        "// Icons from game-icons.net, CC BY 3.0 (Zeromancer's CC0); see GAME_ICONS.md.\n\n"
        "/// A drawing from game-icons.net: one path on a 512-unit grid, filled.\n"
        "public enum GameIcon: String, CaseIterable, Sendable {\n"
        + "\n".join(cases)
        + "\n\n    public static let grid = 512.0\n\n"
        "    /// Who drew it, for the credits.\n"
        "    public var author: String {\n        switch self {\n" + "\n".join(authors) + "\n        }\n    }\n\n"
        "    public var path: String {\n        switch self {\n" + "\n".join(paths) + "\n        }\n    }\n}\n"
    )
    CREDITS.write_text(
        "# Icons\n\nThe game's pictures are icons from [game-icons.net](https://game-icons.net), "
        "used under [CC BY 3.0](https://creativecommons.org/licenses/by/3.0/) "
        "(Zeromancer's under CC0). They are converted to paths by `scripts/game_icons.py`; "
        "the app credits them in Settings.\n\n| In the app | Icon | By | Licence |\n|---|---|---|---|\n"
        + "\n".join(credits) + "\n"
    )
    print(f"{len(icons)} icons -> {OUT.name} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
